### ISSUE TITLE
[BUG] 让1pctl 默认== 1pctl help 吧

### ISSUE THREAD

**Issue by BlueNoob** [1Panel-dev/installer#4]
### 1Panel 版本

1.9.1

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/4169222/e9a291e2-a1d6-41b9-9471-de9bc86c8b2c)
[BUG] 让1pctl 默认== 1pctl help 吧
这个设计逻辑，着实有点那啥...

### 期待的正确结果
直接敲1pctl，==  1pctl help

**Comment by wanghe-fit2cloud** [comment]
已提交，下个版本发布。

**Comment by BlueNoob** [comment]
> 已提交，下个版本发布。

能否把1pctl 缩短成  1p ？
bt 敲起来是真方便

**Comment by wanghe-fit2cloud** [comment]
> > 已提交，下个版本发布。
> 
> 能否把1pctl 缩短成 1p ？ bt 敲起来是真方便

暂不考虑。
